---
default_stages: [commit, manual]
exclude: "CHANGELOG.md"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: no-commit-to-branch
        args: ['-b', main', '-b', master', '-b', trunk']
  - repo: https://github.com/lovesegfault/beautysh.git
    rev: v6.2.1
    hooks:
      - id: beautysh
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/hadolint/hadolint
    rev: v2.8.0
    hooks:
      - id: hadolint-docker
  - repo: https://github.com/executablebooks/mdformat
    rev: "0.7.11"
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
        exclude: ^docs/(changelog|license|readme)\.md$
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: "v6.0.0"
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.8
    hooks:
      - id: actionlint-docker
        args: ['--ignore', 'input "generatereleasenotes" is not defined in action "ncipollo/release-action@v1".']
